config/routes.rb
P4dhack::Application.routes.draw do
  resources :posts, :except => [:index, :edit, :update]
  resources :event_names, :only => [:index, :create]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions]
  devise_scope :user do
    match '/users/sign_out(.:format)', {:action=>"destroy", :controller=>"devise/sessions", :via => :delete, :as => :destroy_user_session }
    match '/users/login', {:action=>"login", :controller=>"users", :via => :get, :as => :new_user_session }
  end

  get '/users/current' => 'users#current', :as => :current_user
  get '/users/login' => 'users#login', :as => :login_user
  get '/users/:provider/:user_key' => 'users#show', :as => :user
  get '/users/edit' => 'users#edit', :as => :edit_user
  put '/users/update' => 'users#update', :as => :update_user
  delete '/users/current' => 'users#destroy', :as => :destory_current_user

  get '/users/:user_id/posts/:year/:month/:day' => 'users::posts#day', :as => :user_day_posts, :year => /\d+/, :month => /\d+/, :day => /\d+/
  get '/users/:user_id/posts/:year/:month(.:format)' => 'users::posts#month', :as => :user_month_posts, :year => /\d+/, :month => /\d+/

  get '/policy' => 'pages#policy'
  get '/terms' => 'pages#terms'
  root :to => 'posts#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <title>kintain</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=0.5">
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <!-- Le styles -->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!-- Le fav and touch icons -->
  <link href="/assets/favicon.ico" rel="shortcut icon">
  <link href="/assets/apple-touch-icon.png" rel="apple-touch-icon">
  <script charset="utf-8" src="//widgets.twimg.com/j/2/widget.js"></script>
  <script src="//platform.twitter.com/widgets.js"></script>
  <script type="text/javascript">(function(d) {var s = d.createElement('script'); s.type = 'text/javascript'; s.async = true;s.src = '//static.mixi.jp/js/plugins.js#lang=ja';d.getElementsByTagName('head')[0].appendChild(s);})(document);</script>
  <%= render 'shared/ga' %>
  <%= yield :head %>
  <%= render 'shared/og_graph', {
    title: '勤怠戦隊キンタイン',
    type: "website",
    url: 'http://kintain.herokuapp.com',
    image: 'http://kintain.herokuapp.com/images/logo.png',
    description: "家を出た、会社へ着いた。会社を出た、家へ着いただけを簡単に管理。気軽にソーシャル勤怠管理するなら、勤怠戦隊へお任せを！",
  }
  %>
</head>
<body class="<%= yield :body_class %>">
	<div id="overlay">
		<div id="wrapper">
      <% unless request.path == login_user_path %>
      <header>
        <div id="logo_s"><%= link_to image_tag("logo_s.png"), root_path %></div>
        <% if user_signed_in? %>
          <div id="currentuserstatus">
            <%= image_tag current_user.image, :class => :face %>
            <%= link_to current_user.name, current_user_path%>
            <%= link_to t('.nav.logout'), destroy_user_session_path, :method => :delete %>
          </div>
        <% end %>
      </header>
  <% end %>
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<%= yield %>
<%= javascript_include_tag "application" %>
<%= render 'shared/fb_load_js' %>
<footer>
  <p>
    <%= link_to 'kintain', 'https://github.com/ppworks/kintain'%> &copy; <%= link_to 'kkotaro0111', 'http://twitter.com/kkotaro0111' %> &amp; <%= link_to 'ppworks', 'http://twitter.com/ppworks' %> <%=Time.current.year%>
    powered by <%= link_to 'heroku', 'http://heroku.com' %>
  </p>
  <%=render 'shared/sns_buttons', :url => 'http://kintain.herokuapp.com' %>
</footer>
</div>
</div>
</body>
</html>